### ISSUE TITLE
Prefix reconciliation rules

### ISSUE THREAD

**Issue by hrshdhgd** [mapping-commons/sssom-py#216]
Example:
Reconciliation is the following:

```
prefix_synonyms:
     ICD10: ICD10CM
 prefix_expansion_reconciliation:
     ICD10CM: http://test.owl/
```

Rules:
 1. If ICD10 exists and ICD10CM does not exist
      Replace ICD10 => ICD10CM in prefix_map
      AND Replace ICD10 expansion => ICD10CM expansion
      AND Replace ICD10 => ICD10CM in DataFrame

 2. If ICD10 does not exist and ICD10CM exists
      Update ICD10CM expansion in prefix_map

 3. If ICD10 and ICD10CM  exist:
      Do Nothing.

 4. If ICD10 and ICD10CM do not exist
       Do Nothing

@matentzn , does this make sense?

**Comment by hrshdhgd** [comment]
So in the prefix reconciliation step, here's what I have coded so far:

reconciliation.yaml:
```
prefix_synonyms:
    a: c
    b: bravo
    r: rdfs
    o: owl
prefix_expansion_reconciliation:
    c: http://test.owl/c/
    bravo: http://test.owl/bravo
    rdfs: http://www.w3.org/2000/01/rdf-schema#
    owl: http://www.w3.org/2002/07/owl#
```

prefix_map:
```
#curie_map:
#  a: "http://example.org/a/"
#  b: "http://example.org/b/"
#  c: "http://example.org/c/"
#  d: "http://example.org/d/"
#  rdfs: "http://example.org/rdfs/"
#  owl: "http://example.org/owl/"
```

After applying reconciliation:

prefix_map looks like:
```
{
   'a': 'http://example.org/a/', 
   'c': 'http://example.org/c/', 
   'd': 'http://example.org/d/', 
   'rdfs': 'http://www.w3.org/2000/01/rdf-schema#', 
   'owl': 'http://www.w3.org/2002/07/owl#', 
   'skos': 'http://www.w3.org/2004/02/skos/core#', 
   'sssom': 'http://w3id.org/sssom/', 
   'bravo': 'http://test.owl/bravo'
}
```

`skos:` and `sssom:` are added when I just do a simple `read_sssom_table` which comes from [add_built_in_prefixes_to_prefix_map](https://github.com/mapping-commons/sssom-py/blob/bf9c32b7fa346361d7e4b5993b00204fa6060d7f/sssom/context.py#L57).

Questions:
- Does this look like the expected reconciled `prefix_map`?
- Does this cover all possible scenarios?
