### ISSUE TITLE
Bug?: `--mapping-predicate-filter` only accepting URI, not CURIE

### ISSUE THREAD

**Issue by joeflack4** [mapping-commons/sssom-py#457]
## Overview
I tried `--mapping-predicate-filter omoprel:Mapped_from` and it did not work, but `--mapping-predicate-filter https://w3id.org/cpont/omop/relations/Mapped_from` did.

## Command
Syntax: `f'sssom parse {obograph_path} -I obographs-json -o {outpath_sssom} -m {metadata_path}'`
Actual: `sssom parse /Users/joeflack4/projects/owl-on-fhir/test/output/test_defaults/RxNorm.owl.obographs.json -I obographs-json -o /Users/joeflack4/projects/owl-on-fhir/test/output/test_defaults/RxNorm.sssom.tsv -m /Users/joeflack4/projects/owl-on-fhir/test/output/test_defaults/temp-metadata.sssom.yml`

## Inputs
1. Obographs JSON: [RxNorm.owl.obographs.json](https://github.com/mapping-commons/sssom-py/files/12838820/RxNorm.owl.obographs.json.zip)
2. SSSOM Metadata YML: [temp-metadata.sssom.yml](https://github.com/mapping-commons/sssom-py/files/12838825/temp-metadata.sssom.yml.zip)
```yml
curie_map:
  OMOP: https://athena.ohdsi.org/search-terms/terms/
  omoprel: https://w3id.org/cpont/omop/relations/
```
